/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PubblicaAnnuncioRouteImport } from './routes/pubblica-annuncio'
import { Route as TrovaLavoroRouteImport } from './routes/trova-lavoro'
import { Route as TrovaLavoroAreaRouteImport } from './routes/trova-lavoro.$area'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PubblicaAnnuncioRoute = PubblicaAnnuncioRouteImport.update({
  id: '/pubblica-annuncio',
  path: '/pubblica-annuncio',
  getParentRoute: () => rootRouteImport,
} as any)
const TrovaLavoroRoute = TrovaLavoroRouteImport.update({
  id: '/trova-lavoro',
  path: '/trova-lavoro',
  getParentRoute: () => rootRouteImport,
} as any)
const TrovaLavoroAreaRoute = TrovaLavoroAreaRouteImport.update({
  id: '/$area',
  path: '/$area',
  getParentRoute: () => TrovaLavoroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pubblica-annuncio': typeof PubblicaAnnuncioRoute
  '/trova-lavoro': typeof TrovaLavoroRouteWithChildren
  '/trova-lavoro/$area': typeof TrovaLavoroAreaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pubblica-annuncio': typeof PubblicaAnnuncioRoute
  '/trova-lavoro': typeof TrovaLavoroRouteWithChildren
  '/trova-lavoro/$area': typeof TrovaLavoroAreaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pubblica-annuncio': typeof PubblicaAnnuncioRoute
  '/trova-lavoro': typeof TrovaLavoroRouteWithChildren
  '/trova-lavoro/$area': typeof TrovaLavoroAreaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/pubblica-annuncio' | '/trova-lavoro' | '/trova-lavoro/$area'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pubblica-annuncio' | '/trova-lavoro' | '/trova-lavoro/$area'
  id:
    | '__root__'
    | '/'
    | '/pubblica-annuncio'
    | '/trova-lavoro'
    | '/trova-lavoro/$area'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PubblicaAnnuncioRoute: typeof PubblicaAnnuncioRoute
  TrovaLavoroRoute: typeof TrovaLavoroRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pubblica-annuncio': {
      id: '/pubblica-annuncio'
      path: '/pubblica-annuncio'
      fullPath: '/pubblica-annuncio'
      preLoaderRoute: typeof PubblicaAnnuncioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trova-lavoro': {
      id: '/trova-lavoro'
      path: '/trova-lavoro'
      fullPath: '/trova-lavoro'
      preLoaderRoute: typeof TrovaLavoroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trova-lavoro/$area': {
      id: '/trova-lavoro/$area'
      path: '/$area'
      fullPath: '/trova-lavoro/$area'
      preLoaderRoute: typeof TrovaLavoroAreaRouteImport
      parentRoute: typeof TrovaLavoroRoute
    }
  }
}

interface TrovaLavoroRouteChildren {
  TrovaLavoroAreaRoute: typeof TrovaLavoroAreaRoute
}

const TrovaLavoroRouteChildren: TrovaLavoroRouteChildren = {
  TrovaLavoroAreaRoute: TrovaLavoroAreaRoute,
}

const TrovaLavoroRouteWithChildren = TrovaLavoroRoute._addFileChildren(
  TrovaLavoroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PubblicaAnnuncioRoute: PubblicaAnnuncioRoute,
  TrovaLavoroRoute: TrovaLavoroRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
